# Generated by Django 3.0.7 on 2020-07-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog_api', '0002_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
